app:
  customer-srv:
    url: http://localhost:9999/customers
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb:27017/testdb


